// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ydkPlhy3t7lSbogPkTV5Z7iTj90mdDU',
    appId: '1:308746297398:web:8465dc8c3e33b954517897',
    messagingSenderId: '308746297398',
    projectId: 'apart-mate-e0ced',
    authDomain: 'apart-mate-e0ced.firebaseapp.com',
    storageBucket: 'apart-mate-e0ced.firebasestorage.app',
    measurementId: 'G-TDN8X33LEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1AlA09mcvJUEa-un6ylvhPH2WNoG_W3M',
    appId: '1:308746297398:android:a89d09bc20ca740b517897',
    messagingSenderId: '308746297398',
    projectId: 'apart-mate-e0ced',
    storageBucket: 'apart-mate-e0ced.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrQagtqyiTa8i7xudg7hBp0pkZuX06ALM',
    appId: '1:308746297398:ios:d2ff37a1d6a8bec1517897',
    messagingSenderId: '308746297398',
    projectId: 'apart-mate-e0ced',
    storageBucket: 'apart-mate-e0ced.firebasestorage.app',
    iosBundleId: 'com.example.apartmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrQagtqyiTa8i7xudg7hBp0pkZuX06ALM',
    appId: '1:308746297398:ios:d2ff37a1d6a8bec1517897',
    messagingSenderId: '308746297398',
    projectId: 'apart-mate-e0ced',
    storageBucket: 'apart-mate-e0ced.firebasestorage.app',
    iosBundleId: 'com.example.apartmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9ydkPlhy3t7lSbogPkTV5Z7iTj90mdDU',
    appId: '1:308746297398:web:f68a8bd3c7009ea0517897',
    messagingSenderId: '308746297398',
    projectId: 'apart-mate-e0ced',
    authDomain: 'apart-mate-e0ced.firebaseapp.com',
    storageBucket: 'apart-mate-e0ced.firebasestorage.app',
    measurementId: 'G-WGKR0F230R',
  );
}
